export const TASK_LIST_REQUEST = 'TASK_LIST_REQUEST'
export const TASK_LIST_SUCCESS = 'TASK_LIST_SUCCESS'
export const TASK_LIST_FAIL = 'TASK_LIST_FAIL'

export const TASK_DETAILS_REQUEST = 'TASK_DETAILS_REQUEST'
export const TASK_DETAILS_SUCCESS = 'TASK_DETAILS_SUCCESS'
export const TASK_DETAILS_FAIL = 'TASK_DETAILS_FAIL'
export const TASK_DETAILS_RESET = 'TASK_DETAILS_RESET'

export const TASK_CREATE_REQUEST = 'TASK_CREATE_REQUEST'
export const TASK_CREATE_SUCCESS = 'TASK_CREATE_SUCCESS'
export const TASK_CREATE_FAIL = 'TASK_CREATE_FAIL'
export const TASK_CREATE_RESET = 'TASK_CREATE_RESET'

export const TASK_UPDATE_REQUEST = 'TASK_UPDATE_REQUEST'
export const TASK_UPDATE_SUCCESS = 'TASK_UPDATE_SUCCESS'
export const TASK_UPDATE_FAIL = 'TASK_UPDATE_FAIL'
export const TASK_UPDATE_RESET = 'TASK_UPDATE_RESET'

export const TASK_DELETE_REQUEST = 'TASK_DELETE_REQUEST'
export const TASK_DELETE_SUCCESS = 'TASK_DELETE_SUCCESS'
export const TASK_DELETE_FAIL = 'TASK_DELETE_FAIL'